# Generated by Django 5.0.1 on 2024-02-28 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('ProductId', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=2000)),
                ('Quantity', models.IntegerField()),
                ('CostPrice', models.IntegerField()),
                ('SalePrice', models.IntegerField()),
                ('Pimage', models.ImageField(default='', upload_to='img/products')),
            ],
            options={
                'db_table': 'AddProduct',
            },
        ),
        migrations.CreateModel(
            name='adminData',
            fields=[
                ('Username', models.TextField()),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Password', models.TextField()),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='contactQuary',
            fields=[
                ('Name', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Subject', models.TextField()),
                ('Message', models.TextField()),
            ],
            options={
                'db_table': 'contactQuary',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('Name', models.TextField()),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Password', models.TextField()),
                ('Phone', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('orderNo', models.IntegerField(primary_key=True, serialize=False)),
                ('dateOfOrder', models.DateTimeField()),
                ('Quantity', models.IntegerField()),
                ('TotalAmt', models.IntegerField()),
                ('CompleteTrans', models.BooleanField()),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.addproduct')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.users')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('Phone', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Address', models.TextField()),
                ('orderNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.order')),
                ('Email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.users')),
            ],
            options={
                'db_table': 'UserDetails',
            },
        ),
    ]
