# Generated by Django 5.0.1 on 2024-03-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='CartId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
