# Generated by Django 5.0.1 on 2024-03-25 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_cartitem_cartid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDescip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.addproduct')),
            ],
            options={
                'db_table': 'ProductDescrip',
            },
        ),
    ]
