# Generated by Django 5.0.1 on 2024-03-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_productdescip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdescip',
            old_name='ProductId',
            new_name='Product',
        ),
    ]
