# Generated by Django 5.0.1 on 2024-04-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_rename_productid_productdescip_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dateOfOrder',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
